### ISSUE TITLE
Carrinho de compras

### ISSUE THREAD

**Issue by hashtegner** [hashtegner/shopping-ucs#13]
Ao adicionar um produto ao carrinho de compras, um novo pedido deve ser aberto no sistema, com status "Aberto". 

Além disso, o botão "Adicionar ao carrinho" só deve ser apresentado se o produto possuir estoque.

**Comment by fernahh** [comment]
(cc @martinjungblut)

o que temos que fazer (estava anotado na A4)
- [x] Pegar usuário da sessão
- [x] Implementar CRUD de `CreditCard`
- [ ] Finalizar a compra

**Comment by fernahh** [comment]
- https://github.com/alesshh/shopping-ucs/commit/e6a8f5a5a7928cba6855bc3c210d478d30a35d78
